// Generated by scripts/migrate-urls.mjs.
const ARTICLE_ALIASES = {
  "/2020/01/01/author-2/": "/post/author/",
  "/author/a0025071gmail-com/": "/post/author/"
};

const IMAGE_EXCEPTIONS = {
  "/wp-content/uploads/2018/09/03-150x150.png": "/image/03-150x150--81a165a847.png",
  "/wp-content/uploads/2018/09/03-550x400.png": "/image/03-550x400--74b4b4803e.png",
  "/wp-content/uploads/2018/09/03.png": "/image/03--726029a263.png",
  "/wp-content/uploads/2018/10/vs-230x132.png": "/image/vs-230x132--aeab8a9e41.png",
  "/wp-content/uploads/2018/10/vs-350x202.png": "/image/vs-350x202--b22ea02b98.png",
  "/wp-content/uploads/2018/10/vs-550x400.png": "/image/vs-550x400--982718fbed.png",
  "/wp-content/uploads/2018/10/vs-830x478.png": "/image/vs-830x478--cec168e0b2.png",
  "/wp-content/uploads/2019/05/flask_set_cookie-150x150.png": "/image/flask_set_cookie-150x150--dfc9b9619d.png",
  "/wp-content/uploads/2019/05/flask_set_cookie.png": "/image/flask_set_cookie--39fc085b2f.png",
  "/wp-content/uploads/2019/10/begin.jpeg": "/image/begin--bea4dc8589.jpeg",
  "/wp-content/uploads/2019/11/begin.jpeg": "/image/begin--a874c5dbb2.jpeg",
  "/wp-content/uploads/2019/11/product.png": "/image/product--37d7e0a5e7.png",
  "/wp-content/uploads/2019/12/03-150x150.png": "/image/03-150x150--08de3bb635.png",
  "/wp-content/uploads/2019/12/03-550x400.png": "/image/03-550x400--45e5ec9f01.png",
  "/wp-content/uploads/2019/12/03.png": "/image/03--f84f785647.png",
  "/wp-content/uploads/2020/05/flask_set_cookie-150x150.png": "/image/flask_set_cookie-150x150--d9f5d25f00.png",
  "/wp-content/uploads/2020/05/flask_set_cookie.png": "/image/flask_set_cookie--cb70ec3b46.png",
  "/wp-content/uploads/2020/07/vs-230x132.png": "/image/vs-230x132--7030922c75.png",
  "/wp-content/uploads/2020/07/vs-350x202.png": "/image/vs-350x202--3cd15e741b.png",
  "/wp-content/uploads/2020/07/vs-550x400.png": "/image/vs-550x400--cad8436a45.png",
  "/wp-content/uploads/2020/07/vs-830x478.png": "/image/vs-830x478--3c8544ba2b.png",
  "/wp-content/uploads/2021/08/cloudfunction-150x150.jpg": "/image/cloudfunction-150x150--fa2d335f62.jpg",
  "/wp-content/uploads/2021/08/cloudfunction.jpg": "/image/cloudfunction--573faf22e7.jpg",
  "/wp-content/uploads/2021/09/cloudfunction-150x150.jpg": "/image/cloudfunction-150x150--37c5e342c7.jpg",
  "/wp-content/uploads/2021/09/cloudfunction.jpg": "/image/cloudfunction--0bdc092449.jpg",
  "/wp-content/uploads/2023/05/GA4-即時報表-150x150.jpg": "/image/GA4-即時報表-150x150--66cc5d39d1.jpg",
  "/wp-content/uploads/2023/05/GA4-即時報表-550x400.jpg": "/image/GA4-即時報表-550x400--6250ed82cb.jpg",
  "/wp-content/uploads/2023/05/GA4-即時報表.jpg": "/image/GA4-即時報表--2953e8847a.jpg",
  "/wp-content/uploads/2023/07/GA4-即時報表-150x150.jpg": "/image/GA4-即時報表-150x150--47035d081d.jpg",
  "/wp-content/uploads/2023/07/GA4-即時報表-550x400.jpg": "/image/GA4-即時報表-550x400--bf265eab94.jpg",
  "/wp-content/uploads/2023/07/GA4-即時報表.jpg": "/image/GA4-即時報表--65970d3c56.jpg",
  "/wp-content/uploads/2024/08/product.png": "/image/product--0b64c858ce.png"
};

function decodePathname(pathname) {
  try { return decodeURIComponent(pathname); } catch { return pathname; }
}

function encodePathname(pathname) {
  return pathname.split("/").map((segment) => encodeURIComponent(segment)).join("/");
}

function redirectTarget(url) {
  const pathname = decodePathname(url.pathname);
  const normalized = pathname === "/" || pathname.endsWith("/") ? pathname : `${pathname}/`;
  if (ARTICLE_ALIASES[normalized]) return ARTICLE_ALIASES[normalized];
  const post = normalized.match(/^\/\d{4}\/\d{2}\/\d{2}\/([^/]+)\/$/);
  if (post) return `/post/${post[1]}/`;
  if (IMAGE_EXCEPTIONS[pathname]) return IMAGE_EXCEPTIONS[pathname];
  const image = pathname.match(/^\/wp-content\/uploads\/(?:\d{4}\/\d{2}\/)?([^/]+)$/);
  if (image && /\.(?:avif|gif|jpe?g|png|svg|webp)$/i.test(image[1])) return `/image/${image[1]}`;
  return null;
}

export default {
  async fetch(request) {
    if (request.method !== "GET" && request.method !== "HEAD") return fetch(request);
    const url = new URL(request.url);
    const target = redirectTarget(url);
    if (!target) return fetch(request);
    url.protocol = "https:";
    url.hostname = "www.maxlist.xyz";
    url.port = "";
    url.pathname = encodePathname(target);
    return Response.redirect(url.toString(), 301);
  }
};
